#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
#
# initrd-init: init-bin that runs inside of initrd
#
# Copyright (C) 2019 Vitaly Chikunov <vt@altlinux.org>

PATH=/sbin:/usr/sbin:/bin:/usr/bin

# Required modules for 9p to work under qemu
modprobe 9p
modprobe 9pnet_virtio
modprobe virtio_pci

# 9p mount options: https://www.kernel.org/doc/Documentation/filesystems/9p.txt
#   version=9p2000.L to support linux extensions, like xattr
#   trans=virtio for qemu
#   access=any single connect to 9p server
mount -n -t 9p -o version=9p2000.L,trans=virtio,access=any /dev/root /mnt

exec switch_root /mnt /usr/sbin/vm-init
